apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.Name }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    component: "{{ .Values.Name }}"
